steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/microservices-ecommerce-433602/ecommerce-image-registry/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/microservices-ecommerce-433602/ecommerce-image-registry/products-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY